apiVersion: v1
kind: Secret
metadata:
    name: grafana-oidc
    namespace: monitoring
type: Opaque
stringData:
    GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:ApyhIt3n2V9VhGOOWWCWYs8OjfyEwRuLVm6I9UrW0M96IRzLifpE6Qzt0ZwsVsLFe/mFF8MepSG1PUm3Rsuda5GZiw6oMtMAyQvMs3RYzcSL5vrArA/q3a93tI21QSu1JmW5tGk4d4kLA5XFDAtCkUwbHccdiKF4ejD9/ZT+o9U=,iv:PdAbZw71IMboOWsaU5rGrzw2hR1stTgh/+jEFqTkmQE=,tag:hZndgeF/76/o95q5RL3ieQ==,type:str]
sops:
    age:
        - recipient: age16qvd0tlwjc33cy50qynsuy304hvmat48wxme6yvylk9hj8j8pd6sk6zaz5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHYmtTZjMxUEQyWDU3citG
            SVE1U2Y5VmwyWnJ3WUYrZE0zcnJpUlFrblhnCmh4Rks5bVo5SDBDbG00a3ZWcVdP
            WUpMak9nYWN3ODZidDViaThYeDdwK2MKLS0tIC9lQ05xd0NFbG9BcCtqVU9hRjJU
            Qjg3cUJUZm9aTi9hOWp0alAxYTBmc1EK2fMacqidhV1uS/Sd4XCnAJgw+jRFTXCy
            FW2ZzQCASlQPmjWCP9iluhiBHtV7DTbisiOcsWprtmgBTGdpZwP8FA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-29T17:45:06Z"
    mac: ENC[AES256_GCM,data:3nKr/WW4AM1HZe387reU4TbT1CGEEYFtMwDbuf7Mu0QdLTHecMqouncAj3jE7B8uP+co++d1f9qtsf8JUy6AAUlYJu4wTXc8wKXTeOB1Vfy0upnQn0+0ZnjNUafL/93tLI0ylNQgfOa09GGo6olAl/l8VD0agJSvCKkfSLyKLKM=,iv:as3puhaymgnd8rIUJVI1juDTGIaGyOY6OOBPbG7GFPg=,tag:CgwiHQW5WsL2c0R8Xkxzbg==,type:str]
    encrypted_regex: ^(data|stringData|.*(password|token|secret).*)$
    version: 3.12.1
