apiVersion: v1
kind: Secret
metadata:
    name: argocd-redis
    namespace: argocd
type: Opaque
data:
    auth: ENC[AES256_GCM,data:R9M8tPZdQgqrbaDHl3kyYQwUL/EZP29f,iv:EnxR7xR4/Iy3jn93vcrJRBjYUestsQw3ApQwzNThtC4=,tag:WgUsbIuctche2rVkcK1oaA==,type:str]
sops:
    age:
        - recipient: age16qvd0tlwjc33cy50qynsuy304hvmat48wxme6yvylk9hj8j8pd6sk6zaz5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2bFptRXJad2kvejVJc1BF
            TmZWampCcW5reUh4SUhaZThRaFBUTWxUUFRVCmNJU0Ntc05tZ1F0UWIranAva1Rp
            NVlDRkFZQWhZS3F2ejdrQ29SN2pWUUEKLS0tIGZBMldCVFVKWE9zcjBxU281RllG
            bCtac0dLK2s2YUFOTkFhMCtBSDZSblkKuNCsrogFL6xQE9q+zlITLOJmU0/77hEl
            fsOmMySGsTv8mxrzgjebZqrCbQ0nx0aSVIMiZoj3POl1KRYjKKHpQQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-26T12:32:57Z"
    mac: ENC[AES256_GCM,data:wcZBEUHkhMH9HmsLu8Exdl6uljDDffQ74/PmI3byTfOFxRIP0sVyDINvgfhIYXR8dg2QmZCE7XlFz/dXT/12enCkzw6Hb4qkXg37t6R5/WR8T8Ffakm8Cli5DN8MzYusTvRcgYLEfGNvAn6HXmK01iMzUx/AKlE0UAuKDEPtSYw=,iv:JHbYC7cwOymAj6sPrQQTLOx7IUo51LQpI+vbueKKm6s=,tag:IILO9gY6cIbzNLfSc7E19w==,type:str]
    encrypted_regex: ^(data|stringData|.*(password|token|secret).*)$
    version: 3.11.0
