apiVersion: v1
kind: Secret
metadata:
    name: argocd-secret
    namespace: argocd
    labels:
        app.kubernetes.io/name: argocd-secret
        app.kubernetes.io/part-of: argocd
type: Opaque
data:
    admin.password: ENC[AES256_GCM,data:M59VZ/8GTXG8fFKCnYJ3LDvpBZB9d2B5y28OCfAKFlyRZNCuxLGRSTEZw2eaT7BGnITo0+svSBnqidaPmbSbXSHzh5PxcM+xIZvKL+ccVm8=,iv:kzHPvVNo9Ug/1CEg8D8bKDR1ALuF9Kyc4g40SAs3ZlI=,tag:lukRKBH+CDpuFJjf2iXWQg==,type:str]
    admin.passwordMtime: ENC[AES256_GCM,data:wHOsiM4LaivDJ+gXNdYMzuMA++vYqxVDWq2U9w==,iv:Ynr8BqJcikmJlDMuNJDrRyFupHUoZ7+pOgS7u4zf/tQ=,tag:dT5xwXqJcaQF2ik4RSNgXA==,type:str]
    server.secretkey: ENC[AES256_GCM,data:xvzVV9PWd7G3DvjX549XIg3jhOdp0Lu8o7Hphx+6CdTpEVHXKjdCXHGNFDxDkYvl3ZFbHhF5O3H7RUW8,iv:GJIO688TXIeoXh+hctESY3m3UllofzCQipQvJsj0jOw=,tag:+CSiQIAhNPCD7b40RqYquw==,type:str]
sops:
    age:
        - recipient: age16qvd0tlwjc33cy50qynsuy304hvmat48wxme6yvylk9hj8j8pd6sk6zaz5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBka2N6OCthUnJqN1BqVHYz
            eEQ5cDdSbjZva1RYZEx6SGp5ZFYrVElmbkRzCmlEcGY2ZWYvWHo4bFhzU21EU1Na
            eStqaXdPcER6NTFiMGRRaE9CS3N6aTgKLS0tIEVhWXo5V3R0MXNxcThZVlAvVmpI
            YTJUdytjZDl4RWNyRVJoUmRxMFl3WHcKQhCZwen3JPpcpMsLQ6threiGcvIC1gCM
            hdQxX4J1q2HYQthOswqH0wIOnSugrOeDRifEQ4d3OvUjL3ydVCn8gw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-26T12:32:55Z"
    mac: ENC[AES256_GCM,data:8HljxpF8DQs3yZ6aPXsOt4YfIZctkKHAyryMwFjmwSrbx+ydT0IaQsH4wmsdaizGkez51mR1daX/B2JC4714aXgrZ+60n2QiwCqXRj+by7RubQkem2yCu2sj30EBINa1EwOlKKCLuPChDK05EbDtzm2ccLtiZ9HBWy5WCJW9aoM=,iv:RYzaLlcQf7DeXFqVQERKxhWSXh6oR2i9eRI8SnGrdaQ=,tag:o4aYuqH78026t8jYr6xTqg==,type:str]
    encrypted_regex: ^(data|stringData|.*(password|token|secret).*)$
    version: 3.11.0
