apiVersion: v1
kind: Secret
metadata:
    name: argocd-secret
    namespace: argocd
stringData:
    oidc.authentik.clientSecret: ENC[AES256_GCM,data:lcZ85T2n8O+mNLRUaJU9zHfJzMeBtvHi/4icNKGhfmQaTBVStFAzb8Iccg0WSWyEG6u3o0nUes9kkr9Vhd+f4qTtyYSOhO12ES41vrb+ssVZcR7P5s5SrRysVovlRLiDyaYy8CEM+oB4Uz1dYXwlV5fvdn0/Sbd5QoVGS+I69+I=,iv:EqeAjChSPIydrJRnLjnbwzfw115cSibv/k6K2rFAWoY=,tag:nbzHBFXJbAb4+nFapaIPAA==,type:str]
sops:
    age:
        - recipient: age16qvd0tlwjc33cy50qynsuy304hvmat48wxme6yvylk9hj8j8pd6sk6zaz5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5dE9NUjN1VDdudVBCUFV6
            U3h0WW41TDJLQ1p2YkU2cDF0cjRoK2JjQW1JCjh0ZTluTkx4OFVjeGp4bGRBUHhh
            UFNxNnVTbXpPc3k5SldSVXBaZENuTzgKLS0tIFQ4ZXdUZjl4QnRibzgzN0FPWXBr
            Z2VNMDRJRWtqelFmOEFPOVlEaU5EUlEKj+tKW/YbD2wkzjiYUsK+faCsyAZ9qkcJ
            SnDDN4LvU9nvnAea4hDREtwJNtWKTk1Xc+qdeaUzfdDc4NvNzOvhdw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-20T08:36:30Z"
    mac: ENC[AES256_GCM,data:ywalYH2MiMIUw021X165SvOfl50kD5VS57U+zqeB0x3+NmtVY1MoDVRWwGPYCCMFgWdVe9Hw7JOv2EktonAHKgXlBL4Y4I1eo/ERVZWzn85YnBnrN4csrqDFOT8gweU68TGqNEgJl/H4CSsVZILabFPrKIwxozFWwPwV/kYw3y0=,iv:lrfOPI81OOlp8cd0dVFPc8fS/cr0Wa0k21v273mlmTc=,tag:9ny+P/bT1TbyNvXJAL/wiA==,type:str]
    encrypted_regex: ^(data|stringData|.*(password|token|secret).*)$
    version: 3.12.2
