deployment:
  podAnnotations:
    prometheus.io/port: "8082"
    prometheus.io/scrape: "true"
global:
  systemDefaultRegistry: ""
image:
  repository: rancher/mirrored-library-traefik
  tag: 3.5.1
api:
  insecure: true
  dashboard: true
priorityClassName: system-cluster-critical
providers:
  kubernetesIngress:
    publishedService:
      enabled: true
service:
  type: LoadBalancer
  ipFamilyPolicy: PreferDualStack
  loadBalancerIP: 192.168.10.120
  annotations:
    metallb.universe.tf/address-pool: traefik-pool
tolerations:
- key: CriticalAddonsOnly
  operator: Exists
- effect: NoSchedule
  key: node-role.kubernetes.io/control-plane
  operator: Exists
