---
# Source: wiki/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: wiki
  namespace: wikijs
  labels:
    app.kubernetes.io/name: wiki
    app.kubernetes.io/instance: wiki
    app.kubernetes.io/version: "latest"
