# Encrypt this file with SOPS before committing
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:3OAmhNeFzgdc/2X/isAmfYUrACv3ajNdcb9WaDdASMN/LoDNcZ6g1A==,iv:NfhYmrfmKyFBktIJsCSry+UxuSmb1QhRzqOoQmtbKt8=,tag:fygZQ1epTrVWBrcoLJwPUQ==,type:str]
sops:
    age:
        - recipient: age16qvd0tlwjc33cy50qynsuy304hvmat48wxme6yvylk9hj8j8pd6sk6zaz5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwODVyN3lmUy9sNDdsaC9B
            by9hOEZrZGVlbzZzblFwWTNVWVJKdytuY2dFClhhdVEvWkFiRTdVSXpHU2VSamFk
            Z3paMWpUWWlLY3pmSTJXR1YyMjVBSU0KLS0tIGMvbnJMay9ESitHWEd0WTBwQzh5
            cldKVjJpdk1uOWdZc3VBbm1sM0pySG8KUAsef4uIpmzq84YSUacbS2GiS3lDnED4
            3Y4HG8eNBMvhHFeiJVi8BMS8ugX7x7GpAPzeIosArQ2pPKC1kwEGtQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-03T18:53:51Z"
    mac: ENC[AES256_GCM,data:wvtL46bXUdApuMY6La7AkSKnDYYgGYNBZEV/iqUBNbC2KcAEy3y23Y8X4vYbVbW52dWbEqafPNxTI+C+vcthdqVluEEg6PUhSAwu5egqtiPhphnRJHzVp0m087PeFYPkJJux5Joy1FBAntJ+BuptM2pwrRK7Mj/z/hnbQx5uxDc=,iv:fZ7mSIXhzq3peUufqo5kS13NJp5q68M9XGWPm9zk724=,tag:pDB0wenbdzjm5Y76Op5lww==,type:str]
    encrypted_regex: ^(data|stringData|.*(password|token|secret).*)$
    version: 3.11.0
