apiVersion: v1
kind: Secret
metadata:
    name: ghcr-pull-secret
    namespace: dr-downloader
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:a5oG+SSI85o+EXY/GkfrMIU51lhmH8mHbxZyWirOuFPzFLPDZ2n+wlf9lHvpuYsaROXXSRmStWsmUWplSBvZQ+6VVLS1PWO9IYgSSoju+NdbmS9JVjjHZl3Ej1auGP0wuQ==,iv:G74jv3XN/JTP8l+iZk4az/Z4lYKsGzx5mcSeGseDWXs=,tag:7rVpcD86A+XHT+Xrs7M2Dw==,type:str]
sops:
    age:
        - recipient: age16qvd0tlwjc33cy50qynsuy304hvmat48wxme6yvylk9hj8j8pd6sk6zaz5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUcGhwSWc5dnV0VHdEYWkw
            UDRoc1hsOW9NWUowNy9ObHNkNU0rMVEzbUZRCnBTRnNEV1NoRUlFZ2xFWW5IMkh5
            QjB3bHdZcWlsL0tOakk3V3pDQXdkTEkKLS0tIHU2bDNYZjA4UVVETXhIaXFySEdY
            cFJ6anBiWWNOSFQrYmRpSXpsV0NQRm8KGiNS5f4sC3Spdhebk0V2tY7eno3UnY1s
            9GNMUOEL2h/mqwxI0c240ibM8Sb6N9lsJIRSK5y4OpwB4booA9I6gA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-24T17:47:59Z"
    mac: ENC[AES256_GCM,data:5ijTEe8SIZMOE8h/trQ2pT9KVmygOrqhk7ROoyctKhAujRa6bmGVM4aK0eRAAisqK1mbSOKOvdG1nwTISJAdTp5i6JLzK1NSE+Oidk2ISxFYkwzHTicjmxqDqrs/Wk9RJN+CYws4HOhag+F6PPHeW2qRuLkWg9HHn4hhvT9bKMI=,iv:/2ZfXHwUv5nrz7EJFUQ1FSFPjRatbSxnckSPOOr2eq0=,tag:m1inmCapkVQGFXBH5WlZMg==,type:str]
    encrypted_regex: ^(data|stringData|.*(password|token|secret).*)$
    version: 3.12.1
