apiVersion: v1
kind: Secret
metadata:
    name: kuma-heartbeat
    namespace: dr-downloader
type: Opaque
stringData:
    bluey: ENC[AES256_GCM,data:WJ0Hf7TJa/mBmWF9lAuvgxB04eDjwR2qZaDcY6qhHUxkxgsYyAnpYv+Dz9K/QhCAZuSZefttu9K+y1U5yUaVL9qnpA==,iv:9tDiTO4C8l7qcZVbv0v0K9PSwsVRBTZdTjsFmtKLquM=,tag:5NSNUNKaeRsLXjzZqdaNYg==,type:str]
    pokemon: ENC[AES256_GCM,data:5N50wvhGeD+IS9AyAyBfV2iKnPZDQffiUbiN3UkyP9PT190/cWxrogVP2kUBK0b04i2jTsefKmxQg5JQgS45jrD6cA==,iv:IgJ/pEigrbi6fXxoxKnlb3Qhs0czz5C86xnflR84Tq0=,tag:/KZ6tBL2QC7R2oiukxnoww==,type:str]
sops:
    age:
        - recipient: age16qvd0tlwjc33cy50qynsuy304hvmat48wxme6yvylk9hj8j8pd6sk6zaz5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwaG9FTkJjKzNkUHgzbzlt
            T05TT1hoc2k5SlhFUDJ3SVFITndkWGxvZ1dFCjErS0pxSkJlZmVUZXRFK3BVSk85
            TDQ2ZVNJVW42Q3RWS1ZadjJaUUpmZUkKLS0tIDB2ay9ONU14WVE5QUpWRTlaWTZr
            NHViZUp3QzVUck1ONjAydTVhWnFYT2sKzzxCJxZrk517VFuHMKRrpjEEaHal4iEY
            lcHhFEMq2fUPKFdGxDmZiaGVE12K9GMjycbzg81R9wcQmKoHTPiw3w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-24T18:29:57Z"
    mac: ENC[AES256_GCM,data:ULYkTnZpo49eBWcizb1Nw7zrVd05Hc4Umj4CZcaGGW0Gjo5kMh5egpEnT3f5QA56DvMdlF+1d0iwYj+qwa3/nciyVb0Dby6n9TOJCCbvQXiuYMBdQZh6CDAWqdG7mspKMjAi4pwVv6sSoQ0nPnK0L1j6iy4/G3vKEiam1qzBThw=,iv:h3Iz+Pcu4d4YohGl4J+RNOxAGHJ2OvB8ClLlciGaaH0=,tag:Re6ZMvhHEPj2W/cMfM5tqw==,type:str]
    encrypted_regex: ^(data|stringData|.*(password|token|secret).*)$
    version: 3.12.1
