# Encrypt this file with SOPS before committing
apiVersion: v1
kind: Secret
metadata:
    name: authentik-secrets
    namespace: authentik
type: Opaque
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:qaOCGDXF4IESRq3F7LlUSZnw7YYb9JnIq0bUxth4eEK+jCPDcauQ2SKi2bI=,iv:hhKtQqkjEH/nvKka0ik9QPOSdUfVW99TxL2Va9I/bEQ=,tag:8kuaLc5qubnN2YLpZ3lfIA==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:CH3WPOif6z6/,iv:gzqhnQnqDl9rRtV6+wn+ZS5bA6P+3nsY9D9LYt9WWA8=,tag:PjbkAwWwsE5zex+rANM1NQ==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:Lqr2jbPu4Oco,iv:ra4aTT1Io3xicbJODyZa77XE4duapN6ZAa2Ao7GQnxc=,tag:XP+RjpS82tqoimX3gVI1DA==,type:str]
    AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:JP0YMAsQX0D96azyC81uH2R5MHYJkmuzTgbTz+yzHgoOjC4Z54SPoATr61K7cIysdhbb1eOb8Npp/D0k+95d61MwQm47l2MoCmzcaRAXI0Q=,iv:N9eDGNGVTDp6ZAxKCP9LEq8NpX2Uoc17h+fqwTe3k/I=,tag:paDVbWeXPUACmA+VQEKIwA==,type:str]
sops:
    age:
        - recipient: age16qvd0tlwjc33cy50qynsuy304hvmat48wxme6yvylk9hj8j8pd6sk6zaz5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiQWJxd0J5K3c4eitTU0ZZ
            bXpBR1hPWDAwKzgwQmRDQTlIWmpxMytlcUJRCkxQTXB6NXliOHdldDI3c1pDZG1w
            OGJOdktnSUQxdDRqYzlmRDFEeHFNODAKLS0tIDNySVcxM0p2T2lrQVRjdnpPOVc3
            MlYvUVQ5aWVuWmZsWi9TYlhvdjVMcG8KJD8a7X1JZ5T/F28HSPHMu6muYb0iVnyM
            DzOi+YN04OqwLJSaYkVVs1RAnzuwbl+ZewvDwZ7hHI0GQZk2WOT9FQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-03T18:44:14Z"
    mac: ENC[AES256_GCM,data:HbR6U4S0Pqy5+bAkVQxED5vqO3JYZu8XpWw3277JUA86JuCbvpFKNEYm/OwIYb9wo0GrB2psZ3DBDjlRA6SyRhaAmJn9EUzTPaJvYWT5DaW95R/1F905XyvxiUEJo44jmH/FVbhApwIi/lFOXe5f7eo1/FN2L5Hw0VNEF5Uam4o=,iv:SEwy5DaZD+BsCTGNO4eP+Rt+VUvIt1E9ZFZtMbpDCtY=,tag:C9x0+GPiImaSec0x392GNg==,type:str]
    encrypted_regex: ^(data|stringData|.*(password|token|secret).*)$
    version: 3.11.0
