apiVersion: v1
kind: Secret
metadata:
    name: kuma-heartbeat
    namespace: authentik
type: Opaque
stringData:
    postgres-backup: ENC[AES256_GCM,data:nZBOHZODzs9u4XfHeq+2aWiJw4h0gGXKKduY5reECZW0rWppTbCNjSBJjTYfIuJ3Z+cdTHPaK4XHBEWK1ZrSks2wCA==,iv:cFg4orBPrer4pueiD1wD/+jWqlJ268S0v9thknVyEwM=,tag:LxgAqJ4hJs91e2dH5yBfbg==,type:str]
sops:
    age:
        - recipient: age16qvd0tlwjc33cy50qynsuy304hvmat48wxme6yvylk9hj8j8pd6sk6zaz5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBybTh0NGdZeHJjOThkaDE4
            T1Z2d1I4TnkrN0NpR1lCUitEcmIzdEdnVFFzCldWSHlreE9ac3JGajZRc2N2ZGFx
            MWgxZVRzSE93SUgwSDZpV3htdUkvaGsKLS0tIGU5VG5tMlJNZmlDUXNLcDFLZlE5
            Nko3bUJFQzFpNExPdjR2RGxjWUhzZm8KzsAwnry/JiEXrmevjg5XYBRI7UPCiglK
            I3tEsGUQ7K6EnF0fZ8EpDJe4k+6lkz94kJKDhsHT3CwuCXJBRK7/6w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-24T18:34:20Z"
    mac: ENC[AES256_GCM,data:pdbXkgfI3zD6a/njCTggfyPcOJGJpWYLLiL1DvOhDrgDqvqSJe4zR9yxPoqiWXpCY5PynZQDnysSKFWCXfqNUh0anKH6uugYNit8Jt0AHIp8OAHwhNFfZO4fdHksESQZc6hnfpUaNV9eGQ44fN8q64uFqfF4VdmnT62B6JRiAeU=,iv:kD85MiyE8UOxgZ6jU27UCtWBuM9/kVZQOgjN0jRHrnw=,tag:YLOGUK3tWp9r+VJ8mMBkRA==,type:str]
    encrypted_regex: ^(data|stringData|.*(password|token|secret).*)$
    version: 3.12.1
