apiVersion: v1
kind: Secret
metadata:
    name: kuma-heartbeat
    namespace: wikijs
type: Opaque
stringData:
    postgres-backup: ENC[AES256_GCM,data:iGq4+gwS1Ey2EJcijLbA3g11R68Dk1znmC01vLRNzXH9kTn2bMaDObk4ypq2ulUaGklgnxIUZDht5Ph4fUGuX1NJeQ==,iv:zzUy9NhsMyGxBOZl1Zqt6Qn0Q6x/jMNGHK70xeNziWw=,tag:zsqRFDT2sE1VyHG7uVjtBw==,type:str]
sops:
    age:
        - recipient: age16qvd0tlwjc33cy50qynsuy304hvmat48wxme6yvylk9hj8j8pd6sk6zaz5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvaHdaUk1tQUVodzVMVkg0
            U1dEV1VoUG55YzlKaXJpY0VZOXV3N0lzU3p3CmNWcmlpL3lCVGszSU9VU2Rrbmt2
            VjI4UVZnSFBHSGlvQTRGSTIrY0c2bEkKLS0tIEdqSlcrMGpHOFNJNHhHRjltQUpj
            clllTjk3NUYyckxSODd3UndhREh1QzgKV7je1AUiKZplkpKgNpf6YhZQBmT1cWJT
            3UyEReU2eQhxXFvVHzBB1xLCcByfqtX1O7FoCvtqsIwJONdcx2Cgyg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-24T18:34:20Z"
    mac: ENC[AES256_GCM,data:6CCybQ2j2HS13HsK6zqoyQzdUqK2ciFkTalTii09EcXKJjJIs3E0wh0eH5FE/WjYLxRecNzAjmKuBkx0SSsv0hG5Vkr5Ts673qSRyg/dhp2xykP5PkJG4PtbqYAMhWrg6E2MD0HOti9A1iR6MSDhqxYVKes1Jnmti/vhR0Xtmd4=,iv:LOsQPERYWY9AFs46dC5f2iHRb8SdU5fVX1pFcXErXkg=,tag:ZJu2MVItFt85bCup2k5cGA==,type:str]
    encrypted_regex: ^(data|stringData|.*(password|token|secret).*)$
    version: 3.12.1
