# Encrypt this file with SOPS before committing
apiVersion: v1
kind: Secret
metadata:
    name: postgres-backup-secrets
    namespace: wikijs
type: Opaque
stringData:
    BACKUP_S3_KEY: ENC[AES256_GCM,data:N0QCfNpkDjER,iv:s92M4z5LOoM02nSE/MiHGJSK3ZehdH0I+bqxX894iME=,tag:wtlksheHKPBe8YxpaR/07g==,type:str]
    BACKUP_S3_SECRET: ENC[AES256_GCM,data:nC7kRgxSv/s=,iv:hZ5S8YvCNs2YbxPBRTKBfHp/HfNBOAXI6mnrytxud7I=,tag:IOPnhtJEWnn31Ru6daPayg==,type:str]
    BACKUP_S3_PATH: ENC[AES256_GCM,data:RDBzVt8bOsQWBQaincDmxdPAB4gagLs=,iv:7kkZ4mZFNfenCQqK6bbks7DZgAvTYcWlThaROvXIFzA=,tag:1lLgQhgGYVlufkmnnSbVmw==,type:str]
    BACKUP_S3_HOST: ENC[AES256_GCM,data:S+KhaJXwIQvT7rOSXC0ketTyag==,iv:AaweBgdIJ3Nyj02aLSX8wxcS1PJEiNLVlMEIPJS9fRg=,tag:FC/hcFic1eg67lH82mQZFw==,type:str]
    BACKUP_S3_HOST_BUCKET: ENC[AES256_GCM,data:9n8axWgpjY5W0p3pAtD7IqMsjA==,iv:F7qrLllWSSpQjS9peakA1XcHKDKOPvUXIU1vqQT9Exc=,tag:ft/PSl5YELaLxq54nyNWvQ==,type:str]
sops:
    age:
        - recipient: age16qvd0tlwjc33cy50qynsuy304hvmat48wxme6yvylk9hj8j8pd6sk6zaz5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhWEk3YjhZWitBdTdJTmVx
            dTN5Tm1iM2d4MjBya29KS3B4RXoxbkZPQkE0CldWZ3BkaEttNmZhdlg2V2VmdGpB
            N3RwcEtGNWhoWWtyVkVyWVJlWU90aXcKLS0tIDlORVVkOERNR1JaYWsrWGlVRzla
            TFFmSG1PL1JaN2FxLzN5N2xXTlFvY2sKEh1o3F2uQkYD+0laHxuxucdZ+TInosxx
            6cPW2zOb7eBX/TICjjbuTaBqT/Gk1olm2/+LpHmF1ovY9ud5Ws/qfw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-03T18:56:32Z"
    mac: ENC[AES256_GCM,data:DpNxueKXxqErAr37Mhtvg03eaz70zWrgY1CeNBiPNa8erCtILB3FkR0TVKZHcP9kYhNpQ/ruslhPRNPX7DWteMtjrRR7QYaNGLZTiK7sRfEd6mQzpfRBD0QWgBkaHn8P3Or/OT82dRk62ezqBdmcqcCO+PFl8+oVONEtdSlVVak=,iv:P4Gg/wm/7MSZG7Hn+ap2p/qEpg7mAkgLxJ6YeOLcfwo=,tag:9QBfZwREHdredrsBlGVkwA==,type:str]
    encrypted_regex: ^(data|stringData|.*(password|token|secret).*)$
    version: 3.11.0
