# Encrypt this file with SOPS before committing
apiVersion: v1
kind: Secret
metadata:
    name: wikijs-secrets
    namespace: wikijs
type: Opaque
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:BYnrA30DQUMHbp8jtiHEP2sliruifyzAnOjJ/IAAANdTXwjOdC93ATAajGk=,iv:l6VAU1fjtNVjjEOkitza/O3kpIfhMSbCwezf6nTe7l8=,tag:PdB8zdA/UffHi27e9vZr/w==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:Jdoe0AGp,iv:c6SBWRNWnxGJQLYCWVsTsY/1JBTZ5iopvOPdDKGIxck=,tag:2tRIWQMmqa0CtYF7LJVU1w==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:WNCtkA==,iv:gWeJzuZVvxtvXTJqiG9KYCW33wkwarO8LKAsMiuF/28=,tag:v9SxGXoDqyUoyJReR4pE9Q==,type:str]
    WIKIJS_SECRET_KEY: ENC[AES256_GCM,data:poHpabHSEpOoonpRHYf7pUpD0wCppFwIWMOqmCKnabwsy46NJEnm58XyCJw=,iv:fyRGw2iLxeiN4tWqBjA9Mle0CptHvKvhgY1h2rQIaKw=,tag:p85UMz+jsIm3Z/Dp4vEkyg==,type:str]
sops:
    age:
        - recipient: age16qvd0tlwjc33cy50qynsuy304hvmat48wxme6yvylk9hj8j8pd6sk6zaz5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkT1JHQm5lbXlaM2xZWjVS
            N3ZjVzZXMkQyVjFjbVNKcUpuZkhyMGwvS1JBCi9jSW5ETFFOdG4zcWJZZ3UyMkto
            c29tZEo0eUFMMGM2UnhKVlQzOWtPUzQKLS0tIFpUeWdCcHo5Mm0xSTIrS29aQmFP
            NWRPeTMvQnV0QmNnbVZyRjlrN2lzTUEKAV8Qx+UWs9T/1P3kwO/hS8Q9D3yaePYB
            Ip6Sqhv1mWHkbIudUatD6YR1bSBzc083VOhIm1QFe4R5q2ehgtC0jQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-03T18:56:37Z"
    mac: ENC[AES256_GCM,data:+e4KdGLInyApimSWD+J9LDYHLb/28Wk9ZJeOvA/Lv8PW6MPf7XTWchSkzJQQF5DsDgyw/CRTZr63hvsWj1GogPwgUCPPNuUpyBSFlhr7fezzk2a9KsBLh5Tp9MCJBwA/p+uFtqEVEn5Untw8EXp7vC3TXxg8lQMbXBs+vC2GhG4=,iv:NUoN9Zm3ukR46xvFDLtzdFP/BHw4wenqe4HjvTGudfI=,tag:DuYvlKEYU4DVqVu3z8cEog==,type:str]
    encrypted_regex: ^(data|stringData|.*(password|token|secret).*)$
    version: 3.11.0
