apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sa-hardening
  namespace: argocd
spec:
  project: homelab
  source:
    repoURL: https://github.com/Frostar/k3s
    targetRevision: HEAD
    path: core/sa-hardening
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
