---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: secrets-authentik
  namespace: argocd
spec:
  project: homelab
  source:
    repoURL: https://github.com/Frostar/k3s
    targetRevision: HEAD
    path: secrets/authentik
  destination:
    server: https://kubernetes.default.svc
    namespace: authentik
  syncPolicy: {}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: secrets-cert-manager
  namespace: argocd
spec:
  project: homelab
  source:
    repoURL: https://github.com/Frostar/k3s
    targetRevision: HEAD
    path: secrets/cert-manager
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy: {}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: secrets-dump-jobs
  namespace: argocd
spec:
  project: homelab
  source:
    repoURL: https://github.com/Frostar/k3s
    targetRevision: HEAD
    path: secrets/dump-jobs
  destination:
    server: https://kubernetes.default.svc
    namespace: postgres-dump-jobs
  syncPolicy: {}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: secrets-longhorn
  namespace: argocd
spec:
  project: homelab
  source:
    repoURL: https://github.com/Frostar/k3s
    targetRevision: HEAD
    path: secrets/longhorn-system
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
  syncPolicy: {}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: secrets-wikijs
  namespace: argocd
spec:
  project: homelab
  source:
    repoURL: https://github.com/Frostar/k3s
    targetRevision: HEAD
    path: secrets/wikijs
  destination:
    server: https://kubernetes.default.svc
    namespace: wikijs
  syncPolicy: {}
