apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  project: homelab
  source:
    repoURL: https://github.com/Frostar/k3s
    targetRevision: HEAD
    path: core/traefik
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
  ignoreDifferences:
    # k3s injects this annotation on services automatically
    - group: ""
      kind: Service
      name: traefik
      namespace: kube-system
      jsonPointers:
        - /metadata/annotations/svccontroller.k3s.cattle.io~1disablelb
