# Wiki Ingress
# Service running in wikijs namespace
# Protected with Authentik middleware

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wiki
  namespace: wikijs
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.middlewares: default-security-headers@kubernetescrd,authentik-authentik@kubernetescrd
    cert-manager.io/cluster-issuer: letsencrypt-cloudflare
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - wiki.j-frost.dk
    secretName: wiki-tls
  rules:
  - host: wiki.j-frost.dk
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: wiki
            port:
              number: 80
