apiVersion: v1
kind: Secret
metadata:
    name: renovate-ghcr-hostrules
    namespace: renovate
type: Opaque
stringData:
    RENOVATE_HOST_RULES: ENC[AES256_GCM,data:xttKCC8NKO6J2kRdRXkprwuvF6ra486gvMtS2ayfzgnerCzWU7s5F0GATtDOLEMTbNgeYez4BYO6RFcScfN9Va603iFjQO3HQ0vX4YUA3LrhoWGjXEMs0grBAVuyXU3INnknckaFhiNLJ921zc0t8T6A8FCd90CJdFX+RK1WEAGkxZEZvEqVCWUlJMQop17AAulzVwsDUey5HDfXn9o2ByKN1GpJl4WOFXsuNua2ffslCCqLsBBW4/CtqvvOs9zLxFCTph1JqqFQCrTO5ZCfBGYO93SMX0+NpnG/rcL/8VrrfM7o7/n4Kc2bqA==,iv:jMUojfQM6hJianHpobABPVkN0Je3pwjIUMYcF3X2GuM=,tag:PPwIzxxntKt3hEYnQ3tZgA==,type:str]
sops:
    age:
        - recipient: age16qvd0tlwjc33cy50qynsuy304hvmat48wxme6yvylk9hj8j8pd6sk6zaz5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLQ1F0NEVzK0YzTUJVY2ZY
            TUZrT3FRRkxhRm5CeVlka0E5UFlvVExUbGdJCmJBVm1GcFNZaWRtOVZkdnN4b3p4
            cUp6bTZmS2lQUjl6dGIrL00zcDVONDgKLS0tIGdvZ2N0b1hYS1pWQTAwS3NWV1Vp
            dVM3RFhkN0ZtQjhhSk8rdFhvNmRqajAKGee0gm59WnXsSiL6aLJZ9VKyGnQWmvkw
            mxemU0rllo3ve/aD+gCqPl7W4//gVnBB4FWn1jYp1gcMIdIjQdAkmQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-10T08:48:26Z"
    mac: ENC[AES256_GCM,data:ZFW+dQH5dxg2f28tuZhzUvaw4B+H1ogMtKfZXxDZ62ACRocJlHN1Lf3gbm4m8NEPJVtVb3yYbl2b4KVG8GKUPXYJ4f2GWCMBlvncok5zk8lyy7Sg/SAesse/zFKrDJi6JAR1yGKawzRst/B7iWDQMFD1kFdewY4gR5c/sTMhQ0U=,iv:9FrBqwcaFkZfQm6gEgWC/Qj9vSz8OMTMD0JaC58MeX0=,tag:ZfqDyKHmlhOvZisBncqCjg==,type:str]
    encrypted_regex: ^(data|stringData|.*(password|token|secret).*)$
    version: 3.12.1
