apiVersion: v1
kind: Secret
metadata:
    name: renovate-ghcr-hostrules
    namespace: renovate
type: Opaque
stringData:
    RENOVATE_HOST_RULES: ENC[AES256_GCM,data:mnlf0hU22xDjE6nEUdD7e0SuiC9rpAQM1y8FjmyPKJujTxjDJgW6cJ38n5K9tUq3pfiRowHR463C2LiOOURNG8Z5VoLiCkAs8gCF1Gz+lu7+AEl640a8/dfkq02EhnNDrvVn2s9YkgE6Vfu8JAVWwv6Use6S3j2w,iv:PZ7RpYvxb9WGzUHewzyGVcuT+SUh2S+yyJnlipeem4s=,tag:94/PVsEY7FQxo8r3qsZLDg==,type:str]
sops:
    age:
        - recipient: age16qvd0tlwjc33cy50qynsuy304hvmat48wxme6yvylk9hj8j8pd6sk6zaz5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLQ1F0NEVzK0YzTUJVY2ZY
            TUZrT3FRRkxhRm5CeVlka0E5UFlvVExUbGdJCmJBVm1GcFNZaWRtOVZkdnN4b3p4
            cUp6bTZmS2lQUjl6dGIrL00zcDVONDgKLS0tIGdvZ2N0b1hYS1pWQTAwS3NWV1Vp
            dVM3RFhkN0ZtQjhhSk8rdFhvNmRqajAKGee0gm59WnXsSiL6aLJZ9VKyGnQWmvkw
            mxemU0rllo3ve/aD+gCqPl7W4//gVnBB4FWn1jYp1gcMIdIjQdAkmQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-24T17:47:59Z"
    mac: ENC[AES256_GCM,data:JKbELIdgPWc7nkQlrIcL0hniLsPNHM4VYrSgKiOzxpPptvEA4LDQZ5Pkp2+M1womQMyZf/vruQO4XodbC941zk0mDc0iLjn69CzirHqpHlg05U0Qwbm8M75tGNkFX7OoIlMILTGz9qDTyT3/9cA34f+Y13GvWkbu8pzfs0GdFJ8=,iv:94j4l9YRYfCj28wcaJayXsTs5dgNjK6Nuvvw8H0In2A=,tag:qzk33ijA9bWcunsRQcCSzw==,type:str]
    encrypted_regex: ^(data|stringData|.*(password|token|secret).*)$
    version: 3.12.1
