apiVersion: v1
kind: Secret
metadata:
    name: kuma-heartbeat
    namespace: renovate
type: Opaque
stringData:
    renovate: ENC[AES256_GCM,data:/6hfjWUVMcYdOoX4e3l6XZlSj3zoBQLBFktly9xJwiAD1Lp/ptt3rvyM+i2nr/0L03MwTn+YDPcreEfZOYXl/0Q6ow==,iv:X+6S8gco/9RiIIBkHY+ZWezBJzcAEfQPKhUuAQf9wag=,tag:4N1iFdwaw2nfsYVL17ac3g==,type:str]
sops:
    age:
        - recipient: age16qvd0tlwjc33cy50qynsuy304hvmat48wxme6yvylk9hj8j8pd6sk6zaz5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXM3VZUVpwbHhLRG1EbVlw
            VVMwemtxU1FEczFJVDFYd0Y5RkZuUHhTd1U0ClNPNElvU0U1S2JCWmVlMUcxSmhD
            OUhQdU0wK096ZU5GelJnc1FWM3NDZUEKLS0tIGpza09rQzhrKzBkcnJzd0ljQnBM
            OW9Xb3pwM1RzU2hqZmkvakx2R0tHWncKBLSLcHJl8F3UgMA6XREJUJX5X2pdjcjf
            2TeKkYMbdyqxarKVykDuD3TZxpZ1g4Bwa5juf3smVkfm2K3n9EFPAg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-24T18:44:07Z"
    mac: ENC[AES256_GCM,data:l/AFDKgi7Isa++KEFQQr3SyjAb8TPUDeksPxK9b0BjyTGTQK5w0dhEgY/Ishd7uScBElzJ2iR1vDzixk8R56zTSOYy38Hrm4abrKu1AnSlsvHGBcS1qWtkp8BQENoJDCdvWw2sPqzQuX5byjxGlIu5054Xvoa+bs9EcpbMtHsls=,iv:QP2gSGVFqb6obQjsXB8YvPkQlhLrbv6fd3AN47hLkTQ=,tag:Gb4bmhk6GuD4akPTHlf90w==,type:str]
    encrypted_regex: ^(data|stringData|.*(password|token|secret).*)$
    version: 3.12.1
