apiVersion: v1
kind: Secret
metadata:
    name: renovate-token
    namespace: renovate
type: Opaque
stringData:
    RENOVATE_TOKEN: ENC[AES256_GCM,data:WXWlWD81s9fzDlRZOs+PBd8cmasJ954YH86NiCEXKyaF/q3y7iP60w==,iv:nkRV7Rvs0qHIcFHcrkcScHV/gqmxndgK1smnsu8HJpc=,tag:FPmRsjlUtlD4cm1QIZAicQ==,type:str]
sops:
    age:
        - recipient: age16qvd0tlwjc33cy50qynsuy304hvmat48wxme6yvylk9hj8j8pd6sk6zaz5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLNjZIQ21oRFRYSVJPL3By
            TFNyYjQ4NjhMTEtnOWMxVENxcnBuRXdqWWpNClBnbVVid2FoNjNNOVlaRHFEUzNx
            eWRoMCtPS3IzdjZJQk9WQWw5bFRKWjQKLS0tIEt4OE03S2VHc3dkdDZpQ2w5NXlw
            cTdHU2J3a1cvYWdEdWZrZHNvMFptVTgKtKyGOQGICjMwOnoIwbaNgBHzcPtSoBFm
            AFywqer1/ojiDxJDg3/aUKRa2DXV6whN62ofqEFVaWP+7ngh9dX2Nw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-17T20:22:10Z"
    mac: ENC[AES256_GCM,data:6gvu1LAl1WP7XgwkucMgMk2Wv1h64DpFLSPY18t1ckiQF/xXXAVjzOpZmbB2E1KMTLzJwkqlNkOh+1Z2laktLHxXPH7tFYzo3ts5kHNrfGE/207gJkbRnbRH2rXbmwwd/DTsHk6MHcpBLNBUoa/kh/y7Hzfw7H5Xmj9BR4Lxut8=,iv:xkEiuyLjqMwuVe4ka6e/W1WKzHU4Gu2zImkUjCm54m4=,tag:3x1bZJC7YJievcCHp8jCUg==,type:str]
    encrypted_regex: ^(data|stringData|.*(password|token|secret).*)$
    version: 3.12.1
