authentik:
  host: auth.j-frost.dk
  secret_key: ""
externalDatabase:
  existingSecret: authentik-secrets
  existingSecretDatabaseKey: POSTGRES_DB
  existingSecretPasswordKey: POSTGRES_PASSWORD
  existingSecretUserKey: POSTGRES_USER
  host: postgresql.authentik.svc.cluster.local
  port: 5432
  type: postgresql
postgresql:
  enabled: false
server:
  env:
  - name: AUTHENTIK_SECRET_KEY
    valueFrom:
      secretKeyRef:
        key: AUTHENTIK_SECRET_KEY
        name: authentik-secrets
  - name: AUTHENTIK_POSTGRESQL__HOST
    value: postgresql.authentik.svc.cluster.local
  - name: AUTHENTIK_POSTGRESQL__PORT
    value: "5432"
  - name: AUTHENTIK_POSTGRESQL__USER
    valueFrom:
      secretKeyRef:
        key: POSTGRES_USER
        name: authentik-secrets
  - name: AUTHENTIK_POSTGRESQL__NAME
    valueFrom:
      secretKeyRef:
        key: POSTGRES_DB
        name: authentik-secrets
  - name: AUTHENTIK_POSTGRESQL__PASSWORD
    valueFrom:
      secretKeyRef:
        key: POSTGRES_PASSWORD
        name: authentik-secrets
  ingress:
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-cloudflare
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      traefik.ingress.kubernetes.io/router.middlewares: default-security-headers@kubernetescrd
    enabled: true
    hosts:
    - auth.j-frost.dk
    ingressClassName: traefik
    tls:
    - hosts:
      - auth.j-frost.dk
      secretName: authentik-tls
  persistence:
    certs:
      existingClaim: authentik-certs
    media:
      existingClaim: authentik-media
worker:
  env:
  - name: AUTHENTIK_SECRET_KEY
    valueFrom:
      secretKeyRef:
        key: AUTHENTIK_SECRET_KEY
        name: authentik-secrets
  - name: AUTHENTIK_POSTGRESQL__HOST
    value: postgresql.authentik.svc.cluster.local
  - name: AUTHENTIK_POSTGRESQL__PORT
    value: "5432"
  - name: AUTHENTIK_POSTGRESQL__USER
    valueFrom:
      secretKeyRef:
        key: POSTGRES_USER
        name: authentik-secrets
  - name: AUTHENTIK_POSTGRESQL__NAME
    valueFrom:
      secretKeyRef:
        key: POSTGRES_DB
        name: authentik-secrets
  - name: AUTHENTIK_POSTGRESQL__PASSWORD
    valueFrom:
      secretKeyRef:
        key: POSTGRES_PASSWORD
        name: authentik-secrets
  persistence:
    certs:
      existingClaim: authentik-certs
    media:
      existingClaim: authentik-media
