# Encrypt this file with SOPS before committing
apiVersion: v1
kind: Secret
metadata:
    name: dump-jobs-s3-secrets
    namespace: postgres-dump-jobs
type: Opaque
stringData:
    BACKUP_S3_KEY: ENC[AES256_GCM,data:3FjdGUABhA9t,iv:ouzsPUYyGnq03l+37Vm7yrB4nQ537eTCLVW2AghCsNw=,tag:viWYG8LPrng/u1eXsvhcJQ==,type:str]
    BACKUP_S3_SECRET: ENC[AES256_GCM,data:EaYMBKRbkxc=,iv:SQHjkG41szXpAysY4vMF1JZ6p0UVPkuo4X8cK34oGwM=,tag:HvPnmULeM6yUTpm/L2p/2g==,type:str]
    BACKUP_S3_PATH: ENC[AES256_GCM,data:PoNOkIKQ85N5wlka5A2TlvINdt/X44E=,iv:r9M4vVJx7cgO75+qzuvv7eyOfVErPvaRthgAfPlBdYY=,tag:LUBHR8TVEsJBmp+KdU6Rzw==,type:str]
    BACKUP_S3_HOST: ENC[AES256_GCM,data:6oFswOUmFCYJHw/NAlLalvu0eg==,iv:Fjho9cPOmnIInoDlQeLW7lT9R8Nz7bB9FOVtb5hm+cQ=,tag:hAAp/HEisoKBowa+9WjO9Q==,type:str]
    BACKUP_S3_HOST_BUCKET: ENC[AES256_GCM,data:zCaILXdQ0i4SWC6KwY0vywHCAw==,iv:30aBn47cDjZBQzxl3MeiTEV7Xg5ZWoF2WZonThXtRtA=,tag:wJm9/v8i25dcvJ8gDQ9Fng==,type:str]
sops:
    age:
        - recipient: age16qvd0tlwjc33cy50qynsuy304hvmat48wxme6yvylk9hj8j8pd6sk6zaz5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1bEIyM2JtVkdlWE9VZVQw
            QmlRcmI3djBiQ1RmYUJmOEhIQlhZUWVUWGlRCmd6aTVXa28vUlFxakplWlJaNFFQ
            aHhsa2wya3k1NmhNaVBiQ1RFTUh5dncKLS0tIDRtYmFNNTcvTU94VE1XbWxTQkY3
            WWtCKzVDSVh2TUF1TjRxcVY0TGNVbmsKtf7be8qCfL7eUho97GyOX+6A8WqK+Jsd
            uPk3S3rrxp36shqyIFnd0fZhpbqdBQw/PhSy3oPTDaGFVt86wfdJRA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-03T18:08:13Z"
    mac: ENC[AES256_GCM,data:F0otiCpS6DKAhK3sULOtcg0DFPa6Mnoa4HoWzzMTJQYgfU8QD1UNimqHsHs6W0BugIqMB3DUnbtchwfayOJ3vM9MSn7heZQtPnvdab4ppwVsoB69TPzooAMTAN6cxGOCw77AAgyIL0jI4L0AsKVLdIfCnDSnOO5p7Kgy5kmXOdI=,iv:qaer/xOqWRs86AjYdIbO0eUBAH+bHmBnDbgdsHlMBAw=,tag:j2qjNfhS8KWUWZrsCRPSJA==,type:str]
    encrypted_regex: ^(data|stringData|.*(password|token|secret).*)$
    version: 3.11.0
