apiVersion: v1
kind: Secret
metadata:
    name: kuma-heartbeat
    namespace: postgres-dump-jobs
type: Opaque
stringData:
    homeassistant: ENC[AES256_GCM,data:tcPfmjLMC9rNQj7pk3XrWz96CHbgFeDPzNCfbMN3kEOCMuqbRChekbSjYjo8Mneenu61lisg2b3SUNFi2Gs9h7cZ8Q==,iv:jBuL7e4RB6rXX32RUuMgNO6jPQUZdOLC+yxFyJRJWmc=,tag:0HRnx5YOkM0PSfNib84mgA==,type:str]
    nextcloud: ENC[AES256_GCM,data:cm/Ljub+NXjYtagPfAfGS5dSqpxD1a2JqZ2v0tva0YHwwR7wudrsA82GDGFGMFsVRiooAec/A9/XHaNFL2IdhrgeTQ==,iv:DH4sBnNTgrOmQDi940G3nvopoZs5pqDgKLRk+beH9/E=,tag:Wz8OjWk9d0ZQkSo/Om/ERg==,type:str]
sops:
    age:
        - recipient: age16qvd0tlwjc33cy50qynsuy304hvmat48wxme6yvylk9hj8j8pd6sk6zaz5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuV1ZxVjdrYStuaGRzaW02
            R3RCaE1vRHN3VW9CYjVpMkJEMitKa2VJL0I4CkpqUHV4anBGaHFFa2JNZmdTNXNB
            Y0N3UDZ4bUNtU0NyczRDS1lkazFUc28KLS0tIGZ6MUkzYzIrYndSazFjMWVGcTRX
            Rm0ydnVxN2tBUWwzU3l0R20yUkV0YUUKLVmsPkAeYHq6wnn9zNwg5lKNNn6g2FD8
            r1KFMGYuCrFMlc68qfocpqi7Bkm7utRMpVXjofoLzgvywLoq6LeCmA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-24T18:34:20Z"
    mac: ENC[AES256_GCM,data:Lbqm6zWs3WbNF2cqgbeTKtjlzUY1uMegh+1xu2JuT56/Q7/9kr/RUVl/AnnVRzLKhki7WF30aWFZQfbGPGhRM4ulthkxAg261unTT9mZ98xeK28HKD5xl++gplDFIiG97ylHN5fJ+NwmYVilzy2A6MNJU5llZnLZkovFFgNmwCg=,iv:sgf9EAwk4eYr/qZFlLKpTok3oqZcGQEn6PAqHq4p4UQ=,tag:zvZgRshv3+kz+C2G2rE2Gw==,type:str]
    encrypted_regex: ^(data|stringData|.*(password|token|secret).*)$
    version: 3.12.1
