# Encrypt this file with SOPS before committing
apiVersion: v1
kind: Secret
metadata:
    name: postgres-backup-secrets-homeassistant
    namespace: postgres-dump-jobs
type: Opaque
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:JDwDo5+q9un6,iv:37snVh9X9D9z19AI+/C1sHyEfUl1dw0NLcQ+tl2l5zM=,tag:JIhg2bUEWmeohkM8UrUtNA==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:iNlsPDNvEexa6rkSXeCKD/XShmr8Ek5E,iv:PeBGNkX1PpXVJew8qT7io85mok+0yGAflf/UwczZPTE=,tag:zuOj5ebEVSkynWNF1z4+gQ==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:1IVHXlS9jFC2wGTzfg==,iv:3EWD8tYqR62/lds+YJqGaCC1wVSMAiiHK7sLO6IqkLw=,tag:32hsyi7+QQAlnY3Z3iUbvw==,type:str]
    POSTGRES_HOST: ENC[AES256_GCM,data:z+CO7XGn0OR1+PLJsjA=,iv:MP0vOvZevi7OB6FMKc6wGJ9WzDpbx7l7c1HOU2SEtuE=,tag:vo4rmtSPEWpDA87QNs7wLQ==,type:str]
    POSTGRES_PORT: ENC[AES256_GCM,data:ghDmMQ==,iv:X7aEmQalFydkRRDpVCWKmkm3iS6S9rH42SVUtJbqUrQ=,tag:u5rTWmQaYLEJFWAeVddDww==,type:str]
sops:
    age:
        - recipient: age16qvd0tlwjc33cy50qynsuy304hvmat48wxme6yvylk9hj8j8pd6sk6zaz5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHdXFOdzB3OWFmamc5ODlL
            WmhRMitIdzlDWHZzQTR5YjJQK2ZZT0ZzQXhrClBWKzJ0YjkvcmZpc2h4S0Ntbnhx
            V2VoZmlFd2ZuTlREMTMzZVBQN0QrZXcKLS0tIEFrSkx0eVNVVlNBVDFhYkZQOGRi
            OEFmUDRIUjFQcmEyYjlnQldRRW1HajAKp62hXmjs9Uwnnbpye1/fUdEEbQHJ6Ja0
            Jd/ae8LDn0CBY8+5JLcJ9kPs+srTEUXuFEixk74xW9XFJBU/qcjOyA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-03T18:30:36Z"
    mac: ENC[AES256_GCM,data:EVMwk7+VzTx8y94EVA7L5QEqIZ2VIH3jkizd4gA/obVIKK5uVmbZRl8V7a3VaWMt03gkVsRoo6hNNG3FcHfMZNZq7oNu68m1RsDb7jeteM/iamflo6ohY1zsc9slItbBf9jwWgfLT//lzUBe7Btb3T/XODlLuaTUpT9/ZKVcVJc=,iv:kjcts/gaJh5ayeN+clN3w49cRYhffuh/7OEYVx/86/A=,tag:7bLfACEUVroaNOqZ5sggeA==,type:str]
    encrypted_regex: ^(data|stringData|.*(password|token|secret).*)$
    version: 3.11.0
