# Encrypt this file with SOPS before committing
apiVersion: v1
kind: Secret
metadata:
    name: postgres-backup-secrets-nextcloud
    namespace: postgres-dump-jobs
type: Opaque
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:2dgmu+qnU+hD2Q==,iv:MulQrznxcBeQfksxoHOTBMZ11o3TmHbinWS9+v4AsnU=,tag:JPLTtpqiwj4GNXiv1kTuFg==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:tyJbA4s2hgK11w2O5huXX+o0ssUq90NcoXyj5Akr,iv:+hDOSayllqXU6/tnKwELszu+jr2D5A766SVFWC9x3H0=,tag:hv0x/lF8C1vRSkgr/kEeyw==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:YOG8+l4IQzRo,iv:iKWQJhWqmmLNEFIEIAzZzXPEBMx8ZSTArkYMvzwc3p8=,tag:9r5g3gLOrRM++YUlqoCJYw==,type:str]
    POSTGRES_HOST: ENC[AES256_GCM,data:JLabizFG/REAla4MvSY=,iv:650EDxuTtvBN/P9DX1zlri2JcfyPnZcMKvxkEng9lCU=,tag:0FBDmHDolzKtSqPJXAT2Hw==,type:str]
    POSTGRES_PORT: ENC[AES256_GCM,data:cdI4rwI=,iv:DZw9M4hS3d3dt3S+4qv6WK1kKgeE4Hy02m0DKBkfMPY=,tag:hcM5Mj+5OCcaZ3D7LoAaOg==,type:str]
sops:
    age:
        - recipient: age16qvd0tlwjc33cy50qynsuy304hvmat48wxme6yvylk9hj8j8pd6sk6zaz5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyODR1SmRPc2JCclBoTFN0
            QjYrYnFZaEVxWld2Q3o4Y0VEUG5ySUZsNlJRCkRSQk8zaUNBcnU2aC9YaHN0VWFh
            TEVxOWdEY0lwcFB1R2g5b1F0Q2ZIakkKLS0tIGpZV2EzWEllSGRHODk5Q1NPbzBP
            eFA4WWw4S1VUbWZBNTZwK0JxcEFvUVkKe57S80hKpzYA0vdwQJ2dkAyTkjIrg5HN
            PpxkFQWDDuYSFynq7cJR0qH3inZF3OQ3d1t+fRMzGBF9iwjp7eZp1g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-03T18:30:47Z"
    mac: ENC[AES256_GCM,data:ZWNjb5tYnHX6hrhhe4rIRp+h8J8yFfh/jNPLoTfCKtjbSkQJlGfPJ62H9YLeTHMBF8yuyL2qBCohCQncIrX2Up0CB19zaWq/AyXEBri2cEcFgyHYt95DeOQqFzI5HbmHZUCwPWHsAgVbsyiJ33Pv5xzOVTIJmX5bLsO0mpwtTyk=,iv:2cGY5/xsA+bHAMWK5jFkzLIi4kfZ/Wjz1aacyl11vew=,tag:Ci39rFHTFcPd9WBR6FTDew==,type:str]
    encrypted_regex: ^(data|stringData|.*(password|token|secret).*)$
    version: 3.11.0
