# Encrypt this file with SOPS before committing
apiVersion: v1
kind: Secret
metadata:
    name: backup-secret
    namespace: longhorn-system
type: Opaque
data:
    AWS_ENDPOINTS: ENC[AES256_GCM,data:w2zUP/ixYWFZFKb7ZJm+FjjTGWz6c4dTKQB2gVC/CvZpDQoQ,iv:7I7TPjyG2u4TmMmvoUYXlFuLwnnaA6givRAmOYftags=,tag:uLQJchM+pXj6xzMwIeHr/w==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:/5+XQOlpmSCxkMG5bbmuttLo/kbfYWOy22JNkA==,iv:JjFATxKTupKUrqz4SVzKMCWtO6IpcxsbTsJKQShaB/c=,tag:4UVd2eJ08sxtLYBmg06bFw==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:GHhfZPXZ3lBfX9lxB92Po2FGsRvjqmmLZp3JSWvXHN9HlQcBj0HvIZ+faNcPO2RwZR9lScxqPGg=,iv:bgj4fyyRN0ZBOI0+j41d+NTDgtpseZP7+0WhU7TVGwM=,tag:vXEVv2bgrwlXkI9bVhRTvQ==,type:str]
sops:
    age:
        - recipient: age16qvd0tlwjc33cy50qynsuy304hvmat48wxme6yvylk9hj8j8pd6sk6zaz5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUYnA2MGVYcGxRdC9MOUpL
            bTBQVGdNME9Cd2h2ZFpMMzA3TjgrTTEwVDNNCjV6MkhzZ0pYSzQrelg5M0ltaTRJ
            K1NRT3N6cWl2c3ZhOTVyL1I2NTAxNTQKLS0tIEt6ZWpoeXFsbGlUVUwzZHlYSXJp
            RWlodzN2OU12VVhSL0k3UDRiTTVhY2cKfcpG7kstnkOA5Exxe9O6jM32pqeyIbEZ
            AtIzSCXeG0w+jQcxMFfEaEvQJjrDRMUYpTnMDtMjt1M+vg6Mlczq/Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-03T18:37:35Z"
    mac: ENC[AES256_GCM,data:wAv/xeEUDnWRfKC+eq0UHJqA3zNMADK0iDVk8gXlGh3IwXwZMz7BrEyNewxgwhBF8M5fzhglypJWrB8qQgxyfJmH3suSYmnRROeAuPkF9NII9mfo4RLaAB2je70tDCnr2VAEKQ0RSwzO4+mOV4fDKmbm4fNNQMsfjBTTVe4f2Aw=,iv:BNR/xfuiZg1gyeKaCWDntooSTbLrD+tiBFDeT3gVeTE=,tag:w1VG7Ao5LI/6oAMtGKI7IA==,type:str]
    encrypted_regex: ^(data|stringData|.*(password|token|secret).*)$
    version: 3.11.0
