apiVersion: v1
kind: Secret
metadata:
    name: kuma-heartbeat
    namespace: longhorn-system
type: Opaque
stringData:
    daily: ENC[AES256_GCM,data:Ije+OuIr0QFGeKa6dYBoH+dlZz06mCU0kOE8/Zo+EZnwzOrGYfHeGPbs1QFn+AZ8udlKaTsbJIS2nCvaux7W9181dg==,iv:Wt41N3pf0P+0qFpkGiQhJPZj78i6SLi3l+y8p+I2Wdk=,tag:/APfqTlWXg2ZHIz/AtppqA==,type:str]
    weekly: ENC[AES256_GCM,data:vuI1qSR9R9oxFF6u7Kj+Qe+hs7qn7LZjX7du2Y4EAMz06RZsrPIkhs3WOAlAdp5xIqDVOTE4kIGF+CwZILaVz+nAUA==,iv:5a1ksOMOtHfflMBAokHWjmkImuH/qrQVb1ucB1Vfmoo=,tag:YllmGtvN8oSCUh2XvcZt/w==,type:str]
sops:
    age:
        - recipient: age16qvd0tlwjc33cy50qynsuy304hvmat48wxme6yvylk9hj8j8pd6sk6zaz5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJNi81WEpncXQ2Tmx0cWhj
            U3hsNUoyYnQrODFHQlFYcXRwbmdWWWtKS0FzClBIeXE5bmQ3UkloWFU0UWdFTDFW
            RFk2dCt5N1k2SjFyWDd1RnZ0SHVxZWMKLS0tIERBYkZoblk2eWVvcGt6ejM1RExS
            RFM4bVRmb013RjRZOEw0Y29renFlNFUKPkN+SFzuf9KR6zDjA++qVBgtVL81KhLo
            Q/ZswAGMGelJ0Li2TBNftzAmznnav+OUJyNyPqBQaWBONQe3uXRddg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-24T18:49:39Z"
    mac: ENC[AES256_GCM,data:PGrFaISTtMNdWH2xp2QKBRTP2foyZcdVTM8oOCfUWyI6YXQ9w8IefoX1SKR5zQ4ESlW5WUleSHoo5jnR8mCm8xUmA0z0JZlHy96F+Aa4FquwrtLtzux+Qs2KicFRKf7FHWAtYejPGD/3YGG16Z9P5j0QT0X/63fBTPfJNeNuUNQ=,iv:isyWXWu1upd/7LP6oZt/m1hjyS8umyeqwVu7wjyI32k=,tag:cF9YCfGLNZFSjdD5P1eVBw==,type:str]
    encrypted_regex: ^(data|stringData|.*(password|token|secret).*)$
    version: 3.12.1
